import {
  AlertTriangle,
  Award,
  Banknote,
  Bot,
  Clock,
  Database,
  Factory,
  FileBarChart,
  GitBranchPlus,
  Globe,
  Inbox,
  Layers,
  LayoutDashboard,
  ListChecks,
  Network,
  Package,
  ClipboardPlus,
  Route,
  Settings,
  Shield,
  ShieldCheck,
  Shuffle,
  UserPlus,
  Users,
  Workflow,
} from "lucide-react";
import type { DomainConfig } from "@/domains/types";
import { manufacturingLoginConfig } from "./login";
import EnterpriseTwin, { TwinSummary } from "./pages/EnterpriseTwin";
import MultiTwinManager from "./pages/MultiTwinManager";
import SiteDigitalTwin from "./pages/SiteDigitalTwin";
import ConnectorMapping from "./pages/ConnectorMapping";
import RoleBasedDecisions, { FailureModesLibrary } from "./pages/Decisions";
import SupplyChain, { SiteOperations } from "./pages/SupplyChain";
import OrgHierarchy from "./pages/OrgHierarchy";
import ResourceManagement, { AddResource, SharedAllocation, SkillMatrix } from "./pages/Resources";
import {
  BillingAccounting,
  CreateWorkOrder,
  CurrencyIntelligence,
  CustomerInquiries,
  RoutingBuilder,
  ShiftTimesheets,
  WorkOrderLifecycle,
} from "./pages/Operations";
import ExecutiveDashboard, {
  AiAgentGovernance,
  ComplianceLayer,
  Reports,
} from "./pages/Intelligence";

export const manufacturingConfig: DomainConfig = {
  id: "manufacturing",
  label: "Manufacturing",
  tagline: "MANUFACTURING ENTERPRISE OPS",
  defaultRoute: "/enterprise-twin",
  login: manufacturingLoginConfig,
  nav: [
    {
      title: "Enterprise Twin",
      path: "/enterprise-twin",
      icon: Layers,
      group: "Intelligence",
      badgeType: "live",
      badge: "Live",
    },
    { title: "Multi-Twin Manager", path: "/multi-twin", icon: GitBranchPlus, group: "Intelligence" },
    { title: "Site Digital Twin", path: "/site-twin", icon: Factory, group: "Intelligence", badge: "3 sites" },
    { title: "Connector Mapping", path: "/connectors", icon: Database, group: "Intelligence" },
    {
      title: "Role-Based Decisions",
      path: "/decisions",
      icon: Workflow,
      group: "Decision Intelligence",
      badge: "8 roles",
      badgeType: "live",
    },
    { title: "Failure Modes Library", path: "/failure-modes", icon: AlertTriangle, group: "Decision Intelligence" },
    { title: "Supply Chain", path: "/supply-chain", icon: Package, group: "Decision Intelligence" },
    { title: "Site Operations", path: "/site-ops", icon: Settings, group: "Decision Intelligence" },
    { title: "Org Hierarchy", path: "/org-chart", icon: Network, group: "Organisation" },
    {
      title: "Customer Inquiries",
      path: "/customer-inquiries",
      icon: Inbox,
      group: "Organisation",
      badge: 4,
      badgeType: "count",
    },
    { title: "Work Order Lifecycle", path: "/work-orders", icon: ListChecks, group: "Pipeline" },
    {
      title: "Create Work Order",
      path: "/work-orders/create",
      icon: ClipboardPlus,
      group: "Pipeline",
      nested: true,
      parentPath: "/work-orders",
    },
    {
      title: "Routing Builder",
      path: "/work-orders/routing",
      icon: Route,
      group: "Pipeline",
      nested: true,
      parentPath: "/work-orders",
    },
    { title: "Resource Management", path: "/resources", icon: Users, group: "People & Resources" },
    {
      title: "Add Resource",
      path: "/resources/add",
      icon: UserPlus,
      group: "People & Resources",
      nested: true,
      parentPath: "/resources",
    },
    {
      title: "Skill Matrix",
      path: "/resources/skills",
      icon: Award,
      group: "People & Resources",
      nested: true,
      parentPath: "/resources",
    },
    {
      title: "Shared Allocation",
      path: "/resources/shared-allocation",
      icon: Shuffle,
      group: "People & Resources",
      nested: true,
      parentPath: "/resources",
    },
    {
      title: "Shift & Timesheets",
      path: "/timesheets",
      icon: Clock,
      group: "People & Resources",
      badge: 5,
      badgeType: "count",
    },
    { title: "Billing & Accounting", path: "/accounting", icon: Banknote, group: "Finance" },
    { title: "Currency Intelligence", path: "/currency", icon: Globe, group: "Finance" },
    { title: "Executive Dashboard", path: "/dashboard/executive", icon: LayoutDashboard, group: "Intelligence Hub" },
    {
      title: "AI Agent Governance",
      path: "/ai-agents",
      icon: Bot,
      group: "Intelligence Hub",
      badge: 3,
      badgeType: "count",
    },
    { title: "Reports", path: "/reports", icon: FileBarChart, group: "Intelligence Hub" },
    { title: "Administration", path: "/admin", icon: Shield, group: "Platform" },
    { title: "Compliance Layer", path: "/compliance", icon: ShieldCheck, group: "Platform" },
  ],
  routes: [
    { path: "/enterprise-twin", Component: EnterpriseTwin },
    { path: "/enterprise-twin/summary", Component: TwinSummary },
    { path: "/multi-twin", Component: MultiTwinManager },
    { path: "/site-twin", Component: SiteDigitalTwin },
    { path: "/connectors", Component: ConnectorMapping },
    { path: "/decisions", Component: RoleBasedDecisions },
    { path: "/failure-modes", Component: FailureModesLibrary },
    { path: "/supply-chain", Component: SupplyChain },
    { path: "/site-ops", Component: SiteOperations },
    { path: "/org-chart", Component: OrgHierarchy },
    { path: "/customer-inquiries", Component: CustomerInquiries },
    { path: "/work-orders", Component: WorkOrderLifecycle },
    { path: "/work-orders/create", Component: CreateWorkOrder },
    { path: "/work-orders/routing", Component: RoutingBuilder },
    { path: "/resources", Component: ResourceManagement },
    { path: "/resources/add", Component: AddResource },
    { path: "/resources/skills", Component: SkillMatrix },
    { path: "/resources/shared-allocation", Component: SharedAllocation },
    { path: "/timesheets", Component: ShiftTimesheets },
    { path: "/accounting", Component: BillingAccounting },
    { path: "/currency", Component: CurrencyIntelligence },
    { path: "/dashboard", Component: EnterpriseTwin },
    { path: "/dashboard/executive", Component: ExecutiveDashboard },
    { path: "/ai-agents", Component: AiAgentGovernance },
    { path: "/reports", Component: Reports },
    { path: "/compliance", Component: ComplianceLayer },
  ],
};
